#!/usr/bin/env python3
"""
Static validator: a shelled game must actually have its shell.

The text-to-world pipeline is two layers: compose_world writes the MAP
(objects-only level + scene.json ground/water, NO camera) and compose_shell
adds the PRESENTATION shell (camera in scene.json + player/world_clock/
camera singletons spliced into the level + world/rules/10_shell_camera.json).

Re-running compose_world REGENERATES the objects-only level and a
camera-less scene.json — wiping the shell. If you forget to re-run
compose_shell afterward, the scene boots with NO camera (renders black)
and NO player. This validator catches that inconsistency:

  IF a shell was applied (world/rules/10_shell_camera.json exists)
  THEN scene.json must have a non-empty `camera` block
   AND the level's initial_instances must include a player_input_anchor.

A map-only game that was never shelled (no shell-rules file) is skipped —
that's a valid mid-pipeline state, not an error.

Empirical case 2026-05-27: regenerated demo_totem_hills via compose_world
(hero-conditioned asset regen) but didn't re-run compose_shell → scene.json
camera={} + no player → black render. ~10 min of misdirected debugging
(blamed the new .glb) before the missing shell was found.

Usage:
    python3 tools/validators/validate_shell_consistency.py <game> [--strict]
"""

import json
import sys
from pathlib import Path


def validate_game(game_dir: Path) -> list[str]:
    shell_marker = game_dir / "world" / "rules" / "10_shell_camera.json"
    if not shell_marker.exists():
        return []  # never shelled — valid map-only state, nothing to check

    errors: list[str] = []
    scene_p = game_dir / "scene.json"
    if scene_p.exists():
        try:
            scene = json.loads(scene_p.read_text())
        except json.JSONDecodeError as e:
            return [f"scene.json parse error: {e}"]
        cam = scene.get("camera")
        if not isinstance(cam, dict) or not cam:
            errors.append(
                "shell was applied (world/rules/10_shell_camera.json exists) "
                "but scene.json has no `camera` block — the map was likely "
                "regenerated by compose_world without re-running compose_shell. "
                "Re-run: python3 -m tools.visual_layout.compose_shell <game>")
    else:
        errors.append("shell applied but scene.json missing")

    # Player singleton present in the level?
    has_player = False
    for lvl in sorted((game_dir / "levels").glob("*/entities.json")):
        try:
            inst = json.loads(lvl.read_text()).get("initial_instances", [])
        except json.JSONDecodeError:
            continue
        if any(i.get("def") == "player_input_anchor" for i in inst):
            has_player = True
            break
    if not has_player:
        errors.append(
            "shell was applied but no player_input_anchor in any level — "
            "re-run compose_shell to splice the shell singletons back in.")
    return errors


def main() -> int:
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    strict = "--strict" in sys.argv
    if not args:
        print("usage: validate_shell_consistency.py <game> [--strict]")
        return 2
    game = args[0]
    repo = Path(__file__).resolve().parent.parent.parent
    game_dir = repo / "godot" / "data" / game
    if not game_dir.is_dir():
        print(f"[validate_shell_consistency] game dir not found: {game_dir}")
        return 0
    errors = validate_game(game_dir)
    if not errors:
        print(f"[ok] {game}: shell consistent (or map-only)")
        return 0
    print(f"[validate_shell_consistency] FAIL — {game}:")
    for e in errors:
        print(f"  {e}")
    return 1 if strict else 0


if __name__ == "__main__":
    sys.exit(main())
