extends Node

## A* Pathfinding on 2D nav grid.
## Reads nav_grid.json (generated by dungeon_map.py).
## Converts world positions ↔ grid cells.
## Returns path as array of world-space Vector3 waypoints.

var grid: Array = []
var grid_w: int = 0
var grid_h: int = 0
var min_x: float = 0.0
var min_z: float = 0.0
var cell_size: float = 1.0
var walkable_values: Array = [1, 3, 4, 5, 6]  # floor, door, prop, enemy, interactable

var _loaded: bool = false


func _ready() -> void:
	_load_grid()


func _load_grid() -> void:
	var file := FileAccess.open("res://data/nav_grid.json", FileAccess.READ)
	if not file:
		push_warning("[AStar] nav_grid.json not found — run dungeon_map.py first")
		return

	var data = JSON.parse_string(file.get_as_text())
	if not data is Dictionary:
		return

	grid = data.get("grid", [])
	grid_w = data.get("width", 0)
	grid_h = data.get("height", 0)
	min_x = data.get("min_x", 0.0)
	min_z = data.get("min_z", 0.0)
	cell_size = data.get("cell_size", 1.0)
	walkable_values = data.get("walkable_values", [1, 3, 4, 5, 6])
	_loaded = true
	print("[AStar] Grid loaded: ", grid_w, "x", grid_h)


func is_loaded() -> bool:
	return _loaded


func world_to_grid(world_pos: Vector3) -> Vector2i:
	var gx: int = int((world_pos.x - min_x) / cell_size)
	var gz: int = int((world_pos.z - min_z) / cell_size)
	return Vector2i(clampi(gx, 0, grid_w - 1), clampi(gz, 0, grid_h - 1))


func grid_to_world(grid_pos: Vector2i) -> Vector3:
	var wx: float = min_x + grid_pos.x * cell_size + cell_size / 2.0
	var wz: float = min_z + grid_pos.y * cell_size + cell_size / 2.0
	return Vector3(wx, 0, wz)


func is_walkable(gx: int, gz: int) -> bool:
	if gx < 0 or gx >= grid_w or gz < 0 or gz >= grid_h:
		return false
	if gz >= grid.size():
		return false
	var row = grid[gz]
	if not row is Array or gx >= row.size():
		return false
	return row[gx] in walkable_values


func find_path(from_world: Vector3, to_world: Vector3) -> Array:
	## Returns array of Vector3 waypoints from start to goal.
	if not _loaded:
		return []

	var start := world_to_grid(from_world)
	var goal := world_to_grid(to_world)

	if not is_walkable(start.x, start.y):
		start = _nearest_walkable(start)
	if not is_walkable(goal.x, goal.y):
		goal = _nearest_walkable(goal)

	if start == goal:
		return [grid_to_world(goal)]

	# A* algorithm
	var open_set: Array = [start]
	var came_from: Dictionary = {}
	var g_score: Dictionary = {start: 0.0}
	var f_score: Dictionary = {start: _heuristic(start, goal)}
	var closed_set: Dictionary = {}

	var max_iterations: int = grid_w * grid_h  # safety limit
	var iterations: int = 0

	while open_set.size() > 0 and iterations < max_iterations:
		iterations += 1

		# Find node with lowest f_score
		var current: Vector2i = open_set[0]
		var current_f: float = f_score.get(current, 999999.0)
		for node in open_set:
			var nf: float = f_score.get(node, 999999.0)
			if nf < current_f:
				current = node
				current_f = nf

		if current == goal:
			return _reconstruct_path(came_from, current)

		open_set.erase(current)
		closed_set[current] = true

		# Check 4 neighbors (no diagonals — grid-based)
		var neighbors: Array = [
			Vector2i(current.x + 1, current.y),
			Vector2i(current.x - 1, current.y),
			Vector2i(current.x, current.y + 1),
			Vector2i(current.x, current.y - 1),
		]

		for neighbor in neighbors:
			if closed_set.has(neighbor):
				continue
			if not is_walkable(neighbor.x, neighbor.y):
				continue

			var tentative_g: float = g_score.get(current, 999999.0) + 1.0

			if tentative_g < g_score.get(neighbor, 999999.0):
				came_from[neighbor] = current
				g_score[neighbor] = tentative_g
				f_score[neighbor] = tentative_g + _heuristic(neighbor, goal)

				if neighbor not in open_set:
					open_set.append(neighbor)

	# No path found
	return []


func _heuristic(a: Vector2i, b: Vector2i) -> float:
	return abs(a.x - b.x) + abs(a.y - b.y)  # Manhattan distance


func _reconstruct_path(came_from: Dictionary, current: Vector2i) -> Array:
	var path: Array = [grid_to_world(current)]
	while came_from.has(current):
		current = came_from[current]
		path.insert(0, grid_to_world(current))
	return path


func _nearest_walkable(pos: Vector2i) -> Vector2i:
	## Find nearest walkable cell via BFS
	var checked: Dictionary = {}
	var queue: Array = [pos]
	while queue.size() > 0:
		var p: Vector2i = queue.pop_front()
		if checked.has(p):
			continue
		checked[p] = true
		if is_walkable(p.x, p.y):
			return p
		for d in [Vector2i(1, 0), Vector2i(-1, 0), Vector2i(0, 1), Vector2i(0, -1)]:
			var n := Vector2i(p.x + d.x, p.y + d.y)
			if n.x >= 0 and n.x < grid_w and n.y >= 0 and n.y < grid_h:
				queue.append(n)
	return pos


func find_nearest_of_type(from_world: Vector3, cell_type: int) -> Vector3:
	## Find nearest cell of a specific type (e.g., 6=interactable, 5=enemy)
	var start := world_to_grid(from_world)
	var checked: Dictionary = {}
	var queue: Array = [start]
	while queue.size() > 0:
		var p: Vector2i = queue.pop_front()
		if checked.has(p):
			continue
		checked[p] = true
		if p.y >= 0 and p.y < grid.size():
			var row = grid[p.y]
			if row is Array and p.x >= 0 and p.x < row.size():
				if row[p.x] == cell_type:
					return grid_to_world(p)
		for d in [Vector2i(1, 0), Vector2i(-1, 0), Vector2i(0, 1), Vector2i(0, -1)]:
			var n := Vector2i(p.x + d.x, p.y + d.y)
			if n.x >= 0 and n.x < grid_w and n.y >= 0 and n.y < grid_h:
				queue.append(n)
	return from_world  # nothing found
